### ISSUE TITLE
Button alignment

### ISSUE THREAD

**Issue by differentreality** [auth-it-center/class.auth.gr-front-end#3]
In the schedule page, the 'extract schedule' button is **not** aligned with the rest of the buttons on its left.

![screenshot from 2018-04-06 12-50-39](https://user-images.githubusercontent.com/4322737/38415113-2381ae54-3999-11e8-9b97-6f8bc9c08930.png)

**Comment by ninjaki** [comment]
fixed in the current repository

![padding_export](https://user-images.githubusercontent.com/5602081/49646963-85c9d400-fa29-11e8-9e11-eca806c5a8bf.png)
